FROM mcr.microsoft.com/dotnet/aspnet:6.0
RUN rm /etc/localtime --f && ls /usr/share/zoneinfo && cp /usr/share/zoneinfo/Asia/Manila /etc/localtime && echo "Asia/Manila" > /etc/timezone

WORKDIR /app
EXPOSE 80

COPY /src-data .
ENTRYPOINT ["dotnet", "Cinnamon.Api.Data.dll"]