using Cinnamon.Framework.ApiCommand.ApiCore.Activity.Request;
using Cinnamon.Framework.ApiCommand.ApiCore.Activity.Response;
using Cinnamon.Framework.ApiCommand.ApiCore.ExperienceCreationType.Request;
using Cinnamon.Framework.ApiCommand.ApiCore.ExperienceCreationType.Response;
using Cinnamon.Framework.ApiCommand.ApiCore.Favorite.Request;
using Cinnamon.Framework.ApiCommand.ApiCore.Favorite.Response;
using Cinnamon.Framework.Common;

namespace Cinnamon.Web.Modules.ApiAccess.Handlers;

public interface IActivityApiHandler 
{
    Task<AppResult<CreateActivityResult>> CreateActivity(CreateActivityArgs args, string token);
    Task<AppResult<UpdateActivityResult>> UpdateActivity(UpdateActivityArgs args, string token);
    Task<AppResult<GetAllActivitiesResult>> GetAllActivities(GetAllActivitiesArgs? args = null);
    Task<AppResult<GetAllActivitiesResult>> GetPopularActivities(GetAllActivitiesArgs? args = null);
    Task<AppResult<GetExperienceTypesResult>> GetExperienceTypes();
    Task<AppResult<GetExperienceCategoriesResult>> GetExperienceCategories();
    Task<AppResult<GetSubCategoriesResult>> GetSubCategories();
    Task<AppResult<GetActivityImagesResult>> GetActivityImages();
    Task<AppResult<GetAddressResult>> GetAddress();
    Task<AppResult<GetOwnedActivitiesResult>> GetOwnedActivities(GetOwnedActivitiesArgs args, string token);
    Task<AppResult<GetMakerActivitiesResult>> GetMakerActivities(GetMakerActivitiesArgs args);
    Task<AppResult<GetActivityResult>> GetOwnedActivity(int id, string token, GetActivityArgs? args = null);
    Task<AppResult<GetActivityResult>> GetActivity(int id, GetActivityArgs? args = null);
    Task<AppResult<UploadActivityImageResult>> UploadActivityImages(UploadActivityImageArgs args, string token);
    Task<AppResult<UpdateActivityImageOrderResult>> UpdateActivityImageOrder(UpdateActivityImageOrderArgs args, string token);
    Task<AppResult<GetActivitiesByCategoriesResult>> GetActivitiesByCategories(int id, GetActivityArgs? args = null);
    Task<AppResult<GetEnrolledActivitiesResult>> GetEnrolledActivities(GetEnrolledActivitiesArgs args, string token);
    Task<AppResult<GetActivityResult>> GetOwnedActivityByHandler(string handler, string token, GetActivityArgs? args = null);
    Task<AppResult<GetActivityResult>> GetActivityByHandler(string handler, GetActivityArgs? args = null);
    Task<AppResult<GetAllRegionsResult>> GetAllRegions(GetAllRegionsArgs? args = null);
    Task<AppResult<GetAllCitiesResult>> GetAllCitiesByRegionCode(GetAllCitiesArgs? args = null);
    Task<AppResult<GetAllBarangaysResult>> GetAllBarangaysByCityCode(GetAllBarangaysArgs? args = null);
    Task<AppResult<GetRefundableExperienceResult>> GetRefundableExperience(string token);
    Task<AppResult<UpdateScheduleResult>> UpdateActivitySchedule(UpdateScheduleArgs args, string token);
    Task<AppResult<DeleteActivityResult>> DeleteActivityById(DeleteActivityArgs args, string token);
    Task<AppResult<OwnerPricingInclusiveResult>> OwnerPricingInclusive(int id);
    Task<AppResult<GetCouponsResult>> GetCoupons(string token);
    Task<AppResult<CreateCouponResult>> CreateCoupon(CreateCouponArgs args, string token);
    Task<AppResult<UpdateCouponStatusResult>> UpdateCouponStatus(UpdateCouponStatusArgs args, string token);
    Task<AppResult<CreateFavoriteResult>> CreateFavorite(CreateFavoriteArgs args, string token);
    Task<AppResult<RemoveFavoriteResult>> RemoveFavorite(RemoveFavoriteArgs args, string token);
    Task<AppResult<GetFavoritesByCustomerResult>> GetFavoritesByCustomer(GetFavoritesByCustomerArgs args, string token);
    Task<AppResult<ValidateCouponCodeResult>> ValidateCouponCode(ValidateCouponCodeArgs args, string token);
    Task<AppResult<UpdateCouponResult>> UpdateCoupon(UpdateCouponArgs args, string token);
    Task<AppResult<RecommendedActivitiesResult>> RecommendedActivities(string token);
    Task<AppResult<PopularActivitiesResult>> PopularActivities(PopularActivitiesArgs args);
    Task<AppResult<GetExperienceCreationTypeResult>> GetExperienceCreationTypes(GetExperienceCreationTypeArgs args, string token);
    Task<AppResult<GetActivityScheduleTimesResult>> GetActivityScheduleTimes(GetActivityScheduleTimesArgs args);
    Task<AppResult<CreateOngoingActivityScheduleResult>> CreateOngoingActivitySchedule(CreateOngoingActivityScheduleArgs args, string token);
    Task<AppResult<CreateOteResult>> CreateOte(CreateOteArgs args, string token);
    Task<AppResult<UpdateOteResult>> UpdateOte(UpdateOteArgs args, string token);
    Task<AppResult<OteActivityResult>> FindOteByHandler(OteActivityArgs args, string handler);
    Task<AppResult<OteTicketDetailsResult>> TicketDetails(string guid, string token);
    Task<AppResult<CustomerOteResult>> CustomerOte(string token);
    Task<AppResult<OteVerificationResult>> VerifyOTE(OteVerificationArgs args, string token);
    Task<AppResult<DeleteAddOnsResult>>DeleteAddOns(DeleteAddOnsArgs args, string token);
    Task<AppResult<DeleteAddOnResult>> DeleteAddOn(DeleteAddOnArgs args, string token);
    Task<AppResult<OtePerDayResult>> GetOtePerDay(string token);
    Task<AppResult<GenerateEventSharedLinkResult>> GenerateEventSharedLink(GenerateEventSharedLinkArgs args, string token);
    Task<AppResult<OteValidateSharedLinkResult>> ValidateSharedLink(OteValidateSharedLinkArgs args);
    Task<AppResult<VerifySharedEventLinkResult>> VerifySharedEventLink(VerifySharedEventLinkArgs args);
    Task<AppResult<DeleteOnlineEventResult>> DeleteOnlineEvent(DeleteOnlineEventArgs args, string token);
    Task<AppResult<UpdateSharedLinkStatusResult>> UpdateSharedLinkStatus(UpdateSharedLinkStatusArgs args, string token);
    Task<AppResult<DeleteTicketResult>> DeleteTicket(DeleteTicketArgs args, string token);
    Task<AppResult<ActivityFeedResult>> ActivityFeed(ActivityFeedArgs args);
    Task<AppResult<OteAlreadyBookedDatesResult>> OteAlreadyBookedDates(int activityId, string token);
    Task<AppResult<OteScheduleDatesResult>> OteScheduleDates(OteScheduleDatesArgs args, string token);
    Task<AppResult<OteBookedCountResult>> OteBookedCount(OteBookedCountArgs args, string token);
    Task<AppResult<CreateOteWaitlistResult>> CreateOteWaitlist(CreateOteWaitlistArgs args, string token);
    Task<AppResult<GetOteWaitlistByProviderResult>> GetOteWaitlistByProvider(GetOteWaitlistByProviderArgs args, string token);
    Task<AppResult<UpdateOteWaitlistResult>> UpdateOteWaitlist(UpdateOteWaitlistArgs args, string token);
    Task<AppResult<DeleteOteWaitlistResult>> DeleteOteWaitlist(DeleteOteWaitlistArgs args, string token);
    Task<AppResult<GetEmailTemplateResult>> GetEmailTemplate(GetEmailTemplateArgs args, string token);
    Task<AppResult<ProviderQuestionsResult>> ProviderQuestions(ProviderQuestionsArgs args, string token);
}