//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinnamon.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinnamon.Web.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string activity {
            get {
                return ResourceManager.GetString("activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Adaptable: Can come up with alternative ideas when the need arises; Can adjust based on the situation.
        /// </summary>
        internal static string Adaptable {
            get {
                return ResourceManager.GetString("Adaptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this website, you agree to our.
        /// </summary>
        internal static string AlertCookie {
            get {
                return ResourceManager.GetString("AlertCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnamon.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attend.
        /// </summary>
        internal static string attend {
            get {
                return ResourceManager.GetString("attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the experiences you’ll find and meet people to be part of your life, growth, and wellness!.
        /// </summary>
        internal static string attendDescription {
            get {
                return ResourceManager.GetString("attendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become an Activity Provider.
        /// </summary>
        internal static string Become {
            get {
                return ResourceManager.GetString("Become", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a.
        /// </summary>
        internal static string becomeA {
            get {
                return ResourceManager.GetString("becomeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become an Activity Provider.
        /// </summary>
        internal static string becomeAMaker {
            get {
                return ResourceManager.GetString("becomeAMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are still in BETA! All experiences listed are samples only!.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string book {
            get {
                return ResourceManager.GetString("book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you find your experience, just click book and you&apos;re all set! You can even contact the Activity Provider regarding about the experience..
        /// </summary>
        internal static string bookDescription {
            get {
                return ResourceManager.GetString("bookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking is protected by.
        /// </summary>
        internal static string bookingProtected {
            get {
                return ResourceManager.GetString("bookingProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation policy.
        /// </summary>
        internal static string cancellationPolicy {
            get {
                return ResourceManager.GetString("cancellationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string cardNumber {
            get {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Providers are enthusiastic people who may give individual, families, especially those with children, a memorable and exciting opportunity to try something new. Here are the traits of a Activity Provider:.
        /// </summary>
        internal static string cinnamonMakers {
            get {
                return ResourceManager.GetString("cinnamonMakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-up to become an Activity Provider!.
        /// </summary>
        internal static string cinnamonMakerSignup {
            get {
                return ResourceManager.GetString("cinnamonMakerSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Dates.
        /// </summary>
        internal static string clearDates {
            get {
                return ResourceManager.GetString("clearDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022 Cinnamon, Inc..
        /// </summary>
        internal static string companyInc {
            get {
                return ResourceManager.GetString("companyInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Facebook.
        /// </summary>
        internal static string continueFacebook {
            get {
                return ResourceManager.GetString("continueFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue with Gmail.
        /// </summary>
        internal static string continueGmail {
            get {
                return ResourceManager.GetString("continueGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/region.
        /// </summary>
        internal static string countryRegion {
            get {
                return ResourceManager.GetString("countryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown your experience by type, age group and time, this will be reflected in your experience details for customers to choose and book..
        /// </summary>
        internal static string createExperienceDescription {
            get {
                return ResourceManager.GetString("createExperienceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your experience schedule!.
        /// </summary>
        internal static string createExperienceSchedule {
            get {
                return ResourceManager.GetString("createExperienceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Creative: Able to deliver unique and creative experiences.
        /// </summary>
        internal static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit or debit card.
        /// </summary>
        internal static string creditOrDebit {
            get {
                return ResourceManager.GetString("creditOrDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string dates {
            get {
                return ResourceManager.GetString("dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations.
        /// </summary>
        internal static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What it&apos;s all about.
        /// </summary>
        internal static string detailDescription1 {
            get {
                return ResourceManager.GetString("detailDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kilometers away.
        /// </summary>
        internal static string distanceInKM {
            get {
                return ResourceManager.GetString("distanceInKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string editProfile {
            get {
                return ResourceManager.GetString("editProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Card Details.
        /// </summary>
        internal static string enterCardDetails {
            get {
                return ResourceManager.GetString("enterCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a coupon.
        /// </summary>
        internal static string enterCoupon {
            get {
                return ResourceManager.GetString("enterCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Category.
        /// </summary>
        internal static string experienceCategory {
            get {
                return ResourceManager.GetString("experienceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is your experience located?.
        /// </summary>
        internal static string experienceLocated {
            get {
                return ResourceManager.GetString("experienceLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience setup.
        /// </summary>
        internal static string experienceSetup {
            get {
                return ResourceManager.GetString("experienceSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Experiences.
        /// </summary>
        internal static string exploreExperiences {
            get {
                return ResourceManager.GetString("exploreExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in required field.
        /// </summary>
        internal static string fillRequiredField {
            get {
                return ResourceManager.GetString("fillRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2022. All rights reserved.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Quote.
        /// </summary>
        internal static string getQuote {
            get {
                return ResourceManager.GetString("getQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the badge.
        /// </summary>
        internal static string getTheBadge {
            get {
                return ResourceManager.GetString("getTheBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m {0}.
        /// </summary>
        internal static string hiMyName {
            get {
                return ResourceManager.GetString("hiMyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you create an Activity Provider profile that stands out?.
        /// </summary>
        internal static string howToCreate {
            get {
                return ResourceManager.GetString("howToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Take your time building your profile to ensure that it is exactly as you desire..
        /// </summary>
        internal static string howToCreate1 {
            get {
                return ResourceManager.GetString("howToCreate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Connect to your relevant professional organizations to boost your credibility..
        /// </summary>
        internal static string howToCreate2 {
            get {
                return ResourceManager.GetString("howToCreate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Deliver an accurate description of the experience you will provide to assist you get more customers..
        /// </summary>
        internal static string howToCreate3 {
            get {
                return ResourceManager.GetString("howToCreate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Show me what you look like! Put up a profile picture that shows your face clearly..
        /// </summary>
        internal static string howToCreate4 {
            get {
                return ResourceManager.GetString("howToCreate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - We may ask you to show your ID so that everyone can feel safe in our community..
        /// </summary>
        internal static string howToCreate5 {
            get {
                return ResourceManager.GetString("howToCreate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity verification.
        /// </summary>
        internal static string identityVerification {
            get {
                return ResourceManager.GetString("identityVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-person - join in the real world to participate actively.
        /// </summary>
        internal static string inPersonType {
            get {
                return ResourceManager.GetString("inPersonType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Intuitive: Able to discern or understand the situation or customer at the onset.
        /// </summary>
        internal static string Intuitive {
            get {
                return ResourceManager.GetString("Intuitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join {0}+ happy customers.
        /// </summary>
        internal static string joinHappyCustomerCount {
            get {
                return ResourceManager.GetString("joinHappyCustomerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey.
        /// </summary>
        internal static string journey {
            get {
                return ResourceManager.GetString("journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your family experience partner.
        /// </summary>
        internal static string landingHeader {
            get {
                return ResourceManager.GetString("landingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities, learnings and events for you and your loved ones.
        /// </summary>
        internal static string landingSubHeader {
            get {
                return ResourceManager.GetString("landingSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string learnMore {
            get {
                return ResourceManager.GetString("learnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your experience!.
        /// </summary>
        internal static string letsDescribeExperience {
            get {
                return ResourceManager.GetString("letsDescribeExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker.
        /// </summary>
        internal static string maker {
            get {
                return ResourceManager.GetString("maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live your passion, share your knowledge, and leave a mark on people&apos;s lives! An Activity Provider is someone who provides experiences on the Cinnamon platform..
        /// </summary>
        internal static string makerDescription {
            get {
                return ResourceManager.GetString("makerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Munificent: Generous in sharing knowledge and experience so that the customer would really see the experience as worth its cost.
        /// </summary>
        internal static string Munificent {
            get {
                return ResourceManager.GetString("Munificent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your experience!.
        /// </summary>
        internal static string nameThatExperience {
            get {
                return ResourceManager.GetString("nameThatExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the title of your experience that people will see first! Make it 
        ///informative and distinctive so that your customers may understand 
        ///what you are offering.
        /// </summary>
        internal static string nameThatExperienceParagraph {
            get {
                return ResourceManager.GetString("nameThatExperienceParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Neighborly: Is a good “neighbor” by creating a safe space for the customer.
        /// </summary>
        internal static string Neighborly {
            get {
                return ResourceManager.GetString("Neighborly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Notable: Can create a notable or memorable experience for the customers.
        /// </summary>
        internal static string Notable {
            get {
                return ResourceManager.GetString("Notable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, let&apos;s talk about what you should stay away from.
        /// </summary>
        internal static string nowLetsTalk {
            get {
                return ResourceManager.GetString("nowLetsTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Nurturing: Takes good care of the customer and has the customer’s welfare in mind.
        /// </summary>
        internal static string Nurturing {
            get {
                return ResourceManager.GetString("Nurturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow your business and lead people on activities you love.
        /// </summary>
        internal static string onboardingHeader {
            get {
                return ResourceManager.GetString("onboardingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live your passion, share your knowledge and leave a mark in people&apos;s lives!.
        /// </summary>
        internal static string onboardingSubHeader {
            get {
                return ResourceManager.GetString("onboardingSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online - join via video conferencing software (provided by the Activity Provider).
        /// </summary>
        internal static string onlineType {
            get {
                return ResourceManager.GetString("onlineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Open: Has a listening ear to his/her customers. Able to receive feedback well, whether positive or negative.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order summary.
        /// </summary>
        internal static string orderSummary {
            get {
                return ResourceManager.GetString("orderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        internal static string our {
            get {
                return ResourceManager.GetString("our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with.
        /// </summary>
        internal static string payWith {
            get {
                return ResourceManager.GetString("payWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is being verified, we&apos;ll keep you notified..
        /// </summary>
        internal static string pendingVerification {
            get {
                return ResourceManager.GetString("pendingVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price details.
        /// </summary>
        internal static string priceDetails {
            get {
                return ResourceManager.GetString("priceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} night.
        /// </summary>
        internal static string pricePerNight {
            get {
                return ResourceManager.GetString("pricePerNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string privacy {
            get {
                return ResourceManager.GetString("privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to book.
        /// </summary>
        internal static string requestToBook {
            get {
                return ResourceManager.GetString("requestToBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for your trips.
        /// </summary>
        internal static string requiredForYourTrips {
            get {
                return ResourceManager.GetString("requiredForYourTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation won&apos;t be confirmed until the Host accepts your request (within 24 hours)..
        /// </summary>
        internal static string reservationWontConfirm {
            get {
                return ResourceManager.GetString("reservationWontConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string reserve {
            get {
                return ResourceManager.GetString("reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find experiences and activity providers according to your criteria (location, activity, learning, experience).
        /// </summary>
        internal static string searchDescription {
            get {
                return ResourceManager.GetString("searchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest sub-category for approval.
        /// </summary>
        internal static string searchTagMessage {
            get {
                return ResourceManager.GetString("searchTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tags.
        /// </summary>
        internal static string searchTags {
            get {
                return ResourceManager.GetString("searchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string showMore {
            get {
                return ResourceManager.GetString("showMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Signup.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup and join us!.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        internal static string sitemap {
            get {
                return ResourceManager.GetString("sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps to become an Activity Provider.
        /// </summary>
        internal static string stepsToBecome {
            get {
                return ResourceManager.GetString("stepsToBecome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        internal static string streetAddress {
            get {
                return ResourceManager.GetString("streetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support &amp; resources.
        /// </summary>
        internal static string supportResources {
            get {
                return ResourceManager.GetString("supportResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Giving any false or misleading information about who you are..
        /// </summary>
        internal static string Talk1 {
            get {
                return ResourceManager.GetString("Talk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Asking to pay the fees outside of the Cinnamon platform..
        /// </summary>
        internal static string Talk2 {
            get {
                return ResourceManager.GetString("Talk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Creating more than one account. Always remember that you can make more experiences..
        /// </summary>
        internal static string Talk3 {
            get {
                return ResourceManager.GetString("Talk3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Offering a service that is outside the set boundaries of Cinnamon..
        /// </summary>
        internal static string Talk4 {
            get {
                return ResourceManager.GetString("Talk4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 Max.
        /// </summary>
        internal static string textAreaExperienceMax {
            get {
                return ResourceManager.GetString("textAreaExperienceMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total({0}).
        /// </summary>
        internal static string totalCurrency {
            get {
                return ResourceManager.GetString("totalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Activity.
        /// </summary>
        internal static string tryCinnamon {
            get {
                return ResourceManager.GetString("tryCinnamon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of experience are you sharing?.
        /// </summary>
        internal static string typeofExperience {
            get {
                return ResourceManager.GetString("typeofExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string viewProfile {
            get {
                return ResourceManager.GetString("viewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string welcomeTo {
            get {
                return ResourceManager.GetString("welcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you and your clients going to do?.
        /// </summary>
        internal static string whatClientsGoingToDo {
            get {
                return ResourceManager.GetString("whatClientsGoingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Give detailed plans from beginning to end, not a bunch of ideas or 
        ///options.
        ///.
        /// </summary>
        internal static string whatClientsGoingToDoItem1 {
            get {
                return ResourceManager.GetString("whatClientsGoingToDoItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Describe what makes your experience unique—something that 
        ///guests wouldn&apos;t do on their own..
        /// </summary>
        internal static string whatClientsGoingToDoItem2 {
            get {
                return ResourceManager.GetString("whatClientsGoingToDoItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is.
        /// </summary>
        internal static string whatIs {
            get {
                return ResourceManager.GetString("whatIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnamon is an activity, learning, and events marketplace. Our main focus in Cinnamon is to help everyone spend their time on meaningful and fun experiences by connecting you to people who are passionate about sharing their skills and knowledge. We would be honored to partner with you in experiencing life and creating moments!.
        /// </summary>
        internal static string whatIsCinnamon {
            get {
                return ResourceManager.GetString("whatIsCinnamon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where you&apos;ll be.
        /// </summary>
        internal static string whereYoullBe {
            get {
                return ResourceManager.GetString("whereYoullBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we are in Cinnamon?.
        /// </summary>
        internal static string whoWeAre {
            get {
                return ResourceManager.GetString("whoWeAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trip.
        /// </summary>
        internal static string yourTrip {
            get {
                return ResourceManager.GetString("yourTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t be charged until then..
        /// </summary>
        internal static string youWontBeCharged {
            get {
                return ResourceManager.GetString("youWontBeCharged", resourceCulture);
            }
        }
    }
}
