name: Build - develop

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dotnet Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore Web
        run: dotnet restore src/Cinnamon.Web/Cinnamon.Web.csproj
      
      - name: Restore Core
        run: dotnet restore src/Cinnamon.Core/Cinnamon.Core.csproj

      - name: Restore Data
        run: dotnet restore src/Cinnamon.Data/Cinnamon.Data.csproj
      
      - name: Build Project
        run: dotnet build src/Cinnamon.Web/Cinnamon.Web.csproj -c Release -o /output/build

      - name: Public Project
        run: dotnet public src/Cinnamon.Web/Cinnamon.Web.csproj -c Release -o /output/publish
      
      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dev-build
          path: /app/publish/