name: Build - develop

on:
  push:
    branches: [develop]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dotnet Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      # substitute database connection string
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "src/api/Cinnamon.Api.Data/appsettings.json"
        env:
          ConnectionStrings.CinnamonDB: ${{ secrets.DEV_DB_CONNECTION }}

      - name: Restore Framework
        run: dotnet restore src/Cinnamon.Framework/Cinnamon.Framework.csproj

      - name: Restore Api Data
        run: dotnet restore src/api/Cinnamon.Api.Data/Cinnamon.Api.Data.csproj

      - name: Restore Api Core
        run: dotnet restore src/api/Cinnamon.Api.Core/Cinnamon.Api.Core.csproj

      - name: Restore Web
        run: dotnet restore src/Cinnamon.Web/Cinnamon.Web.csproj

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build JS Library
        run: |
          cd src/Cinnamon.Web/JsLib
          echo "mixPanelProjectKey=${{ secrets.MIXPANEL_DEV_KEY }}" >> .env 
          npm install
          npm run build

      - name: Publish Cinnamon.Api.Data Project
        run: dotnet publish src/api/Cinnamon.Api.Data/Cinnamon.Api.Data.csproj -c Release -o output/publish-data

      - name: Publish Cinnamon.Api.Core Project
        run: dotnet publish src/api/Cinnamon.Api.Core/Cinnamon.Api.Core.csproj -c Release -o output/publish-core

      - name: Publish Cinnamon.Web Project
        run: dotnet publish src/Cinnamon.Web/Cinnamon.Web.csproj -c Release -o output/publish-web

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.SERVER_SSH_KNOWN_HOSTS }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy Cinnamon.Api.Data Artifacts to DEV Server
        run: rsync -avz output/publish-data/ cinnamon@${{ secrets.SERVER_IP }}:build-dev/src-data

      - name: Copy Cinnamon.Api.Core Artifacts to DEV Server
        run: rsync -avz output/publish-core/ cinnamon@${{ secrets.SERVER_IP }}:build-dev/src-core

      - name: Copy Cinnamon.Web Artifacts to DEV Server
        run: rsync -avz output/publish-web/ cinnamon@${{ secrets.SERVER_IP }}:build-dev/src-web

      - name: Copy docker-compose
        run: rsync -avz output/docker-compose.dev.yml cinnamon@${{ secrets.SERVER_IP }}:build-dev/docker-compose.yml

      - name: Copy Cinnamon.Api.Data Dockerfile
        run: rsync -avz output/Dockerfile.Data cinnamon@${{ secrets.SERVER_IP }}:build-dev/Dockerfile.Data

      - name: Copy Cinnamon.Api.Core Dockerfile
        run: rsync -avz output/Dockerfile.Core cinnamon@${{ secrets.SERVER_IP }}:build-dev/Dockerfile.Core

      - name: Copy Cinnamon.Web Dockerfile
        run: rsync -avz output/Dockerfile.Web cinnamon@${{ secrets.SERVER_IP }}:build-dev/Dockerfile.Web

      - name: Run Server Script
        run: ssh cinnamon@${{ secrets.SERVER_IP }} 'cd build-dev && sudo docker compose down && sudo docker compose up -d'
