name: Build - develop

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dotnet Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore Web
        run: dotnet restore src/Cinnamon.Web/Cinnamon.Web.csproj
      
      - name: Restore Core
        run: dotnet restore src/Cinnamon.Core/Cinnamon.Core.csproj

      - name: Restore Data
        run: dotnet restore src/Cinnamon.Data/Cinnamon.Data.csproj
      
      - name: Build Project
        run: dotnet build src/Cinnamon.Web/Cinnamon.Web.csproj -c Release -o output/build

      - name: Publish Project
        run: dotnet publish src/Cinnamon.Web/Cinnamon.Web.csproj -c Release -o output/publish
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }} 
          known_hosts: ${{ secrets.SERVER_SSH_KNOWN_HOSTS }}
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Copy Artifacts to DEV Server
        run: scp -r output/publish cinnamon@${{ secrets.SERVER_IP }}:build-dev/src

      - name: Copy docker-compose
        run: scp output/docker-compose.dev.yml cinnamon@${{ secrets.SERVER_IP }}:build-dev/docker-compose.yml
      
      - name: Copy Dockerfile
        run: scp output/Dockerfile cinnamon@${{ secrets.SERVER_IP }}:build-dev/Dockerfile
      
      - name: Copy run server script
        run: scp scripts/run_server.sh cinnamon@${{ secrets.SERVER_IP }}:build-dev/run_server.sh
      
      - name: Run Server Script
        run: ssh cinnamon@${{ secrets.SERVER_IP }} "sh build-dev/run_server.sh"

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dev-build
          path: output/publish/
      